/**
 * POST /api/publish — accepts a Supercut produced by the local CLI
 * (`scripts/dailies.ts`), assigns it a slug (server-generated by default, or
 * an existing one when the caller passes `--update <slug>`), stores it in
 * Netlify Blobs, and returns its published URL.
 */

import type { Config } from '@netlify/functions';
import { deepRedact } from '../../src/lib/parse/redact';
import { generateSlug, getSupercut, putSupercut } from '../../src/lib/store';
import { checkAuthToken, jsonResponse } from './_shared/auth';
import { isPlainObject, isValidSlugShape, validateSupercutShape } from './_shared/validate';

const MAX_BODY_BYTES = 2 * 1024 * 1024; // 2 MB

export default async (req: Request): Promise<Response> => {
  if (req.method !== 'POST') {
    return jsonResponse({ error: 'Method not allowed' }, 405);
  }

  const authError = checkAuthToken(req);
  if (authError) return authError;

  const contentLength = req.headers.get('content-length');
  if (contentLength && Number(contentLength) > MAX_BODY_BYTES) {
    return jsonResponse({ error: 'Payload too large' }, 413);
  }

  const text = await req.text();
  if (new TextEncoder().encode(text).length > MAX_BODY_BYTES) {
    return jsonResponse({ error: 'Payload too large' }, 413);
  }

  let body: unknown;
  try {
    body = JSON.parse(text);
  } catch {
    return jsonResponse({ error: 'Invalid JSON body' }, 400);
  }

  const validation = validateSupercutShape(body);
  if (!validation.ok) {
    return jsonResponse({ error: validation.error }, 400);
  }

  const supercut = validation.value;

  // Slug is server-generated by default. A caller may request re-publishing
  // over an existing slug (`--update <slug>` on the CLI, to refresh a
  // session's replay as it grows) — accepted only when it matches the
  // server's slug shape *and* a supercut with that slug already exists;
  // anything else is rejected rather than silently falling back to a fresh
  // slug, so a typo'd `--update` doesn't quietly publish a duplicate.
  const requestedSlug = isPlainObject(body) ? body.slug : undefined;
  if (requestedSlug !== undefined) {
    if (!isValidSlugShape(requestedSlug)) {
      return jsonResponse({ error: 'slug must be a 10-character lowercase base32 string' }, 400);
    }
    const existing = await getSupercut(requestedSlug);
    if (!existing) {
      return jsonResponse({ error: 'slug does not exist' }, 400);
    }
    supercut.slug = requestedSlug;
  } else {
    supercut.slug = generateSlug();
  }

  // Defense in depth: the local CLI already redacts before publishing, but
  // never trust a client-submitted payload — redact the full object again
  // server-side before it's persisted.
  const { value: redacted } = deepRedact(supercut);

  await putSupercut(redacted);

  // AI narration runs out of the request path, in a background function —
  // /api/narrate returns 202 immediately without waiting on the LLM, so
  // awaiting it here only waits on the trigger, not the generation. Callers
  // opt out per-request with `{ narrate: false }` (the CLI's `--no-narrate`),
  // and the site can be killed server-side with `DAILIES_NARRATE=off`.
  const clientWantsNarration = !(isPlainObject(body) && body.narrate === false);
  if (clientWantsNarration && Netlify.env.get('DAILIES_NARRATE') !== 'off') {
    // Do not make this fire-and-forget: the invocation may freeze before
    // the request leaves, so the narrate trigger would never be sent.
    try {
      const res = await fetch(new URL('/api/narrate', req.url), {
        method: 'POST',
        headers: {
          authorization: req.headers.get('authorization') ?? '',
          'content-type': 'application/json',
        },
        body: JSON.stringify({ slug: redacted.slug }),
      });
      if (!res.ok) {
        console.error(`[publish] narrate trigger failed: ${res.status}`);
      }
    } catch (err) {
      console.error(`[publish] narrate trigger failed: ${err}`);
    }
  }

  const url = `${new URL(req.url).origin}/s/${redacted.slug}`;
  return jsonResponse({ slug: redacted.slug, url }, 201);
};

export const config: Config = {
  path: '/api/publish',
  method: ['POST'],
};
